# Practica inicial de Python

## 1. Introducción a Python y Jupyter
Bienvenidos. En este cuaderno aprenderemos a usar Python.

**Conceptos clave:**
* **Celdas de Código:** Donde escribimos instrucciones para la computadora.
* **Celdas de Texto (Markdown):** Donde explicamos lo que hacemos.
* **Variables:** "Cajas" donde guardamos información (precios, tasas, nombres).

Para ejecutar una celda, presiona `Shift + Enter`.

In [1]:
# Esto es un comentario: Python lo ignora. Pero sirve de guía para recordar lo que estábamos haciendo.

# 1. Creación de variables
capital_inicial = 1000
tasa_interes = 0.05
periodos = 3

# 2. Imprimir las variables
print("Capital Inicial:", capital_inicial)
print(f"Tasa de interés: {tasa_interes * 100}%") # Esta expresión permite ajustar el formato del numero a porcentaje.

Capital Inicial: 1000
Tasa de interés: 5.0%

## 2. Operaciones Matemáticas
Python sigue el orden estándar de operaciones (PEMDAS).
Vamos a calcular el **Valor Futuro (FV)** usando la fórmula de interés compuesto:

$$FV = PV \times (1 + r)^n$$

Donde:
* $PV$: Valor Presente
* $r$: Tasa de interés
* $n$: Número de periodos

In [2]:
# Cálculo del Valor Futuro
valor_futuro = capital_inicial * (1 + tasa_interes) ** periodos

# Nota: En Python, la potencia se escribe con doble asterisco (**)

print(f"El valor futuro de la inversión es: ${valor_futuro:.2f}")
# El :.2f sirve para redondear a 2 decimales

El valor futuro de la inversión es: $1157.63

## 3. Listas (Series de Datos)

En finanzas, rara vez trabajamos con un solo dato. Usualmente tenemos series de precios o portafolios de activos. Las **listas** nos permiten guardar múltiples elementos.

In [3]:
# Una lista de precios de cierre de una acción ficticia
precios_cierre = [100, 102, 101, 105, 107]

# Una lista de tickers
portafolio = ["AAPL", "GOOGL", "TSLA", "AMZN"]

print("Precios:", precios_cierre)
print("Primer activo del portafolio:", portafolio[0]) # Python cuenta desde 0

# Calcular el retorno simple: (Precio Final - Precio Inicial) / Precio Inicial
retorno = (precios_cierre[-1] - precios_cierre[0]) / precios_cierre[0] # Ek indice -1 hace referencia al ultimo elemento de la lista.
print(f"Retorno del periodo: {retorno:.2%}")

Precios: [100, 102, 101, 105, 107]
Primer activo del portafolio: AAPL
Retorno del periodo: 7.00%

## 4. Toma de Decisiones (If / Else)
Podemos programar reglas lógicas. Por ejemplo, una regla simple de compra/venta.

In [4]:
precio_actual = 107
precio_objetivo = 110
stop_loss = 95

if precio_actual >= precio_objetivo:
    decision = "VENDER (Tomar ganancias)"
elif precio_actual <= stop_loss:
    decision = "VENDER (Cortar pérdidas)"
else:
    decision = "MANTENER (Hold)"

print(f"La recomendación algorítmica es: {decision}")

La recomendación algorítmica es: MANTENER (Hold)

## 5. El uso de las Librerías

Python básico es bueno, pero necesitamos herramientas especializadas. Estas herramientas se llaman **librerías**.
La más importante para nosotros es **Pandas** (Panel Data). 
Para usarla, primero debemos importarla:

In [5]:
import pandas as pd
import numpy as np

## 6. Crear una base de datos

En Pandas, una tabla de datos se llama **DataFrame**. Tiene filas y columnas, igual que en **R**.

Vamos a crear una pequeña base de datos de un portafolio manualmente:

In [6]:
# Primero creamos un diccionario con los datos que vamos a emplear en la base de datos

datos_portafolio = {'Ticker': ['AAPL', 'MSFT', 'TSLA', 'AMZN'], 
                    'Empresa': ['Apple', 'Microsoft', 'Tesla', 'Amazon'],
                    'Precio': [150.5, 310.2, 750.0, 3300.0],
                    'Sector': ['Tecnología', 'Tecnología', 'Automotriz', 'E-commerce']}

# Ahora la convertimos en una base de datos

df_acciones = pd.DataFrame(datos_portafolio)

# Y la visualizamos

df_acciones

  Ticker    Empresa  Precio      Sector
0   AAPL      Apple   150.5  Tecnología
1   MSFT  Microsoft   310.2  Tecnología
2   TSLA      Tesla   750.0  Automotriz
3   AMZN     Amazon  3300.0  E-commerce

### Operaciones con bases de datos

Se pueden seleccionar columnas especificas o hacer cálculos rápidos.

In [7]:
# Seleccionar solo la columna de precios
print("Precios del portafolio:")
print(df_acciones['Precio'])

Precios del portafolio:
0     150.5
1     310.2
2     750.0
3    3300.0
Name: Precio, dtype: float64

También se puede usar la posición

In [8]:
print(df_acciones.iloc[1,:]) # Traer la información de la segunda fila

Ticker           MSFT
Empresa     Microsoft
Precio          310.2
Sector     Tecnología
Name: 1, dtype: object

In [9]:
print(df_acciones.iloc[:,3]) # Traer la información de la cuarta columna.

0    Tecnología
1    Tecnología
2    Automotriz
3    E-commerce
Name: Sector, dtype: object

In [10]:
print(df_acciones.iloc[1,2]) # Información de la fila 2 y columna 3

310.2

In [11]:
# Calcular estadísticas rápidas

promedio = df_acciones['Precio'].mean()
print(f"Precio promedio de la acción: ${promedio:.2f}")

Precio promedio de la acción: $1127.67

## 7. Cargar Archivos Externos (CSV)

En la vida real, descargamos los datos de diferentes plataformas.

Vamos a ver como usamos **pandas** para cargar una base de datos.

In [12]:
# Vamos a cargar un archivo csv en una nueva base de datos de Python. El archivo se encuentra en un repositorio publico de GitHub, por lo cual no es necesario descargarlo manualmente.

url_file = "https://raw.githubusercontent.com/salas317/Data/main/GRF/Pasajeros.csv"
df = pd.read_csv(filepath_or_buffer = url_file, sep = ";")

df.head()

         mes  pasajeros
0  1/01/1949        112
1  1/02/1949        118
2  1/03/1949        132
3  1/04/1949        129
4  1/05/1949        121

In [13]:
# Arreglemos la fecha

df = pd.read_csv(filepath_or_buffer = url_file, sep = ";", parse_dates = ["mes"], dayfirst = True)

df.head()

         mes  pasajeros
0 1949-01-01        112
1 1949-02-01        118
2 1949-03-01        132
3 1949-04-01        129
4 1949-05-01        121

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mes        144 non-null    datetime64[ns]
 1   pasajeros  144 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 2.4 KB

In [15]:
# Arreglemos la fecha y que sea el indice

df = pd.read_csv(filepath_or_buffer = url_file, sep = ";", parse_dates = ["mes"], dayfirst = True, index_col = "mes")

df.head()

            pasajeros
mes
1949-01-01        112
1949-02-01        118
1949-03-01        132
1949-04-01        129
1949-05-01        121

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 144 entries, 1949-01-01 to 1960-12-01
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pasajeros  144 non-null    int64
dtypes: int64(1)
memory usage: 2.2 KB